<a href="https://colab.research.google.com/github/amara1973/TP3_S3/blob/main/TP3_AmaraDOUMBOUYA_DataMining_S3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

# Charger le fichier
df=pd.read_csv('/content/sample_data/dataset_ventes_fictives.csv')

# Afficher les 5 premières lignes
df.head()

,ID_Vente,Client,Produit,Quantite,Prix_Unitaire,Montant_Total,Date_Vente,Ville
0,1,Allison Cantu,Souris,16,1459,23344,2025-07-05,Kindia
1,2,Marissa Smith,Ordinateur,2,971,1942,2025-01-29,Kindia
2,3,Steven Baker,Écran,7,1565,10955,2025-01-27,Boké
3,4,Steven Francis,Imprimante,16,358,5728,2025-01-04,Labé
4,5,Sue Jimenez,Ordinateur,6,70,420,2025-02-25,Conakry

In [4]:
df.dtypes

ID_Vente          int64
Client           object
Produit          object
Quantite          int64
Prix_Unitaire     int64
Montant_Total     int64
Date_Vente       object
Ville            object
dtype: object

In [5]:
df.isnull().sum()

ID_Vente         0
Client           0
Produit          0
Quantite         0
Prix_Unitaire    0
Montant_Total    0
Date_Vente       0
Ville            0
dtype: int64

In [6]:
df.describe()

         ID_Vente    Quantite  Prix_Unitaire  Montant_Total
count  500.000000  500.000000      500.00000     500.000000
mean   250.500000    9.934000     1024.22400   10412.570000
std    144.481833    5.819396      563.83593    9154.103223
min      1.000000    1.000000       60.00000     158.000000
25%    125.750000    5.000000      493.50000    3078.000000
50%    250.500000    9.000000     1032.50000    7625.000000
75%    375.250000   15.000000     1512.50000   15266.000000
max    500.000000   20.000000     2000.00000   38120.000000